"""initial schema

Revision ID: 5e15395b2266
Revises: 
Create Date: 2026-03-10 19:31:54.766172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e15395b2266'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_finished_at', sa.DateTime(), nullable=True),
    sa.Column('processing_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batches_batch_key'), ['batch_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_batches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_status'), ['status'], unique=False)

    op.create_table('vendor_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('rfc', sa.String(length=20), nullable=True),
    sa.Column('vendor_name_normalized', sa.String(length=255), nullable=True),
    sa.Column('vendor_name_core', sa.String(length=255), nullable=True),
    sa.Column('rfc_normalized', sa.String(length=20), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_master_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_master_rfc_normalized'), ['rfc_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_master_vendor_name_core'), ['vendor_name_core'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_master_vendor_name_normalized'), ['vendor_name_normalized'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('route', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('rfc', sa.String(length=20), nullable=True),
    sa.Column('fecha_documento', sa.String(length=10), nullable=True),
    sa.Column('tipo_documento', sa.String(length=100), nullable=True),
    sa.Column('nombre_proveedor', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('quality_traffic_light', sa.String(length=20), nullable=True),
    sa.Column('quality_reasons', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.drop_index(batch_op.f('ix_documents_filename'))
        batch_op.drop_index(batch_op.f('ix_documents_file_hash'))
        batch_op.drop_index(batch_op.f('ix_documents_batch_id'))

    op.drop_table('documents')
    with op.batch_alter_table('vendor_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_master_vendor_name_normalized'))
        batch_op.drop_index(batch_op.f('ix_vendor_master_vendor_name_core'))
        batch_op.drop_index(batch_op.f('ix_vendor_master_rfc_normalized'))
        batch_op.drop_index(batch_op.f('ix_vendor_master_id'))

    op.drop_table('vendor_master')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_status'))
        batch_op.drop_index(batch_op.f('ix_batches_id'))
        batch_op.drop_index(batch_op.f('ix_batches_batch_key'))

    op.drop_table('batches')
    # ### end Alembic commands ###
